### ISSUE TITLE
Deployment problems

### ISSUE THREAD

**Issue by Stezii** [Esri/interactive-legend#112]
I am trying to use the configurable app with web maps of my Portal deployment. 
I installed the app successfully (npm install) and hosted the installed environment on a local IIS web server. When I access the /dist folder in the web browser, I get an error from the 4.11 JS API saying "TypeError: a is undefined" (484:54). Afaik see, I did not miss a step from the instructions. Is this issue known?

**Comment by rslibed** [comment]
Can you post a screenshot of the error that you are receiving in the console?

**Comment by rslibed** [comment]
I've also made an update to the application json config. Try pulling in the updates and let me know if it works

**Comment by Stezii** [comment]
This fixes the issue where the default map from AGOL isn't loaded. 
However, the custom web map from my Portal instance still doesn't load. I modified the _portalUrl_ and _webmap_ parameters as follows: 
-   "webmap": "1d538046ee594071a4b953a83e2331fe",
-   "portalUrl": "https://maps.vdl.lu/portal",

Then it says _Could not load an item to display in Main.ts:207:6_
The same params work with the [Calcite Maps](https://github.com/Esri/calcite-maps-styler-template) template without any issue. I also tried setting _"oauthappid": "arcgisWebApps"_. But then, again, I receive _"TypeError: a is undefined"_

**Comment by rslibed** [comment]
@Stezii I've made another update to the app json config. Tested on my machine locally with the portalUrl and webmap id that you have provided and the application runs fine. 

I noticed that the web map that you have provided for the app contains a map image layer. I recommend using web maps that contain feature layers to take full advantage of the app's capabilities.

Here's a link to the app's item page for further information: https://www.arcgis.com/home/item.html?id=5b8ca611fa2e43f7968212d6d4d065cb

**Comment by Stezii** [comment]
I am receiving the following messages when opening /dist via IIS: [https://imgur.com/a/A6nJO2m](https://imgur.com/a/A6nJO2m)
I just modified the params webmap and portalUrl in application.json

**Comment by rslibed** [comment]
Are you still currently having problems? I'm testing on my machine locally and the app seems to run fine with the provided portal and webmap id. 

Based on the screenshot of the console errors, it looks like the issue has to do with the app's boilerplate, `application-base-js`, trying to apply the arcgis js api cdn. Were all dependencies in your `node_modules` successfully installed? Another possibility is that it may have to do with the configuration settings of the server in which you are hosting the web app.

**Comment by Stezii** [comment]
Ups. I forgot to npm install the latest pull. Your commit fixed the issue!

**Comment by rslibed** [comment]
Glad you got the app up and running
